from app.tools.rag_tools import (
    rag_search_tool,
    rag_add_file_tool,
    rag_add_files_tool,
    rag_delete_file_tool,
    rag_stats_tool,
)
from app.tools.db_tools import (
    query_employee_tool,
    get_employee_by_id_tool,
    # add_employee_tool,
    # update_employee_tool,
    # delete_employee_tool,
    query_attendance_tool,
    # add_attendance_tool,
    # update_attendance_tool,
    query_leave_tool,
    get_leave_by_start_date_tool,
    # add_leave_tool,
    # update_leave_tool,
    query_contact_tool,
    # add_contact_tool,
    # update_contact_tool,
    # delete_contact_tool,
)

ALL_TOOLS = [
    rag_search_tool,
    rag_add_file_tool,
    rag_add_files_tool,
    rag_delete_file_tool,
    rag_stats_tool,
    query_employee_tool,
    get_employee_by_id_tool,
    # add_employee_tool,
    # update_employee_tool,
    # delete_employee_tool,
    query_attendance_tool,
    # add_attendance_tool,
    # update_attendance_tool,
    query_leave_tool,
    get_leave_by_start_date_tool,
    # add_leave_tool,
    # update_leave_tool,
    query_contact_tool,
    # add_contact_tool,
    # update_contact_tool,
    # delete_contact_tool,
]